### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/mashaeltsova-photography#13]
## Todo

- [x] ~~Add server-side caching [example1](https://github.com/zeit/next.js/tree/canary/examples/ssr-caching), [example2](https://github.com/Sly777/ran/blob/master/server.js), [example3](https://github.com/fus-marcom/ci-react/blob/master/server.js)~~
- [x] ~`preact` or `inferno` for production [preact-example](https://github.com/zeit/next.js/tree/canary/examples/using-preact), [inferno-example](https://github.com/zeit/next.js/tree/canary/examples/using-inferno)~
- [x] _lazy load_ images [react-lazyload](https://github.com/jasonslyvia/react-lazyload)
- [x] Add service worker configuration [example](https://github.com/zeit/next.js/tree/canary/examples/with-sw-precache)
