### ISSUE TITLE
SEO, Analytics, Other

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/mashaeltsova-photography#14]
## Todo

- [x] ~Add `react-helmet` configuration [example](https://github.com/zeit/next.js/tree/canary/examples/with-react-helmet)~
- [x] Add `react-ga` configuration [example](https://github.com/zeit/next.js/tree/canary/examples/with-react-ga)
- [x] ~Add `no-script` configuraiton [example](https://github.com/zeit/next.js/tree/canary/examples/with-noscript)~
