### ISSUE TITLE
[In-Progress]

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/mashaeltsova-photography#3]
## Todo

- [x] `compose` HOC's.
- [x] `redux-devtools` are still available during `production`.
- [x] Create different form or clean it up some (no styling yet).
- [x] Add _internationalization_ to the form & add keys to `<locale>.json` files.
- [x] Must find way to properly inject env vars on client-side & make sure CircleCi can see them too. See [here](https://github.com/zeit/next.js/tree/master/examples/with-universal-configuration) & [here](https://github.com/zeit/next.js/tree/master/examples/with-dotenv).
- [x] Must test the backend to see if I can `POST` malicious code to it.
- [x] Form level validation.
  
~1. Will `composing` work properly? Already seeing issues with doing this. `<Form />` is who needs `intl` not `<FormContainer />` possibly better to wrap `WithIntl(Form)`?~
