### ISSUE TITLE
BookingForm

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/mashaeltsova-photography#4]
## Todo

- [x] Russian translation [FIXME](https://github.com/rockchalkwushock/mep-api/blob/master/server/utils/index.js#L12).
- [x] ~`onSubmit()` --> Loading View for form.~
- [x] ~`onSubmitFail()` --> Error Modal.~
- [x] ~`onSubmitSuccess()` --> Success Modal.~
- [x] Abstract out elements of form into components for easier styling.
- [x] Make it pretty 💅  😭
